"""Builds Golda's coin as a custom SF Symbol, ios/GoldaWidgets/Assets.xcassets/golda.coin.symbolset.

Usage: python3 ios/tools/coin_symbol.py [output.symbolset]

The Lock Screen and Control Center draw a control's or a round widget's glyph in one colour, and a
control takes only SF Symbols or custom symbols. This draws the coin of tools/coin.py, the source
of both platforms' app icons, in one colour: each facet is filled and shrunk away from its
neighbours, so the cuts between them show as thin gaps where the icon has light and shade. A change
to the coin reaches the symbol by re-running this script.

The output is an SF Symbols template (version 3) with the Regular weight at the medium scale only:
the system scales it for the other sizes and does not vary its weight, which a coin does not need.
"""
import contextlib
import io
import json
import math
import os
import pathlib
import runpy
import shutil
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'ios/GoldaWidgets/Assets.xcassets/golda.coin.symbolset'
NAME = 'golda.coin'

# coin.py writes the Android launcher drawables into the working directory as it runs; run it in a
# scratch directory so only its geometry is taken and the Android files stay untouched.
with tempfile.TemporaryDirectory() as scratch:
    here = os.getcwd()
    os.chdir(scratch)
    try:
        with contextlib.redirect_stderr(io.StringIO()):
            coin = runpy.run_path(str(ROOT / 'tools/coin.py'))
    finally:
        os.chdir(here)

# The template's medium scale: the baseline and the cap line of a 100 pt symbol, the coin centred
# between them like the round system symbols (circle.fill spans about 80 units around the middle).
BASELINE, CAPLINE = 1126.0, 1055.54
LEFT = 1391.0
HEIGHT = 80.0          # the coin from its flat top to its flat bottom, in template units
SIDE_BEARING = 4.0     # the air either side, as the system's round symbols have
GAP = 4.6              # the cut between facets: 1.1 pt at 24 pt, still open at 20 pt

C, R, V = coin['C'], coin['R'], coin['V']
top = min(y for _, y in V)
bottom = max(y for _, y in V)
scale = HEIGHT / (bottom - top)
width = 2 * R * scale
middle = -(BASELINE - CAPLINE) / 2


def place(p):
    # coin.py's 108-unit space to the symbol's: x from the left margin, y from the baseline, up negative.
    return (SIDE_BEARING + (p[0] - (C - R)) * scale, middle + (p[1] - C) * scale)


def inset(polygon, d):
    # Every edge moved inwards by d; a corner is where its two moved edges meet. The facets are
    # convex, so this is their shape shrunk evenly.
    area = sum(a[0] * b[1] - b[0] * a[1] for a, b in zip(polygon, polygon[1:] + polygon[:1]))
    sign = 1 if area > 0 else -1
    lines = []
    for a, b in zip(polygon, polygon[1:] + polygon[:1]):
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy)
        nx, ny = -dy / length * sign, dx / length * sign
        lines.append(((a[0] + nx * d, a[1] + ny * d), (dx, dy)))
    corners = []
    for (p1, d1), (p2, d2) in zip(lines[-1:] + lines[:-1], lines):
        det = d1[0] * d2[1] - d1[1] * d2[0]
        t = ((p2[0] - p1[0]) * d2[1] - (p2[1] - p1[1]) * d2[0]) / det
        corners.append((p1[0] + d1[0] * t, p1[1] + d1[1] * t))
    return corners


def path(points):
    return 'M' + ' L'.join(f'{x:.3f} {y:.3f}' for x, y in points) + ' Z'


facets = []
for face in coin['faces']:
    flat = [place(p) for p in face]
    # Drop repeated corners (a fan's last rim point can sit on its first), which have no edge.
    flat = [p for i, p in enumerate(flat) if math.dist(p, flat[i - 1]) > 1e-6]
    facets.append(path(inset(flat, GAP / 2)))

right = LEFT + width + 2 * SIDE_BEARING
guide = 'fill:none;stroke:#27AAE1;opacity:1;stroke-width:0.5;'
margin = 'fill:none;stroke:#00AEEF;stroke-width:0.5;opacity:1.0;'
lines = []
for scale_name, base in (('S', 696.0), ('M', BASELINE), ('L', 1556.0)):
    cap = base - (BASELINE - CAPLINE)
    lines.append(f'  <line id="Baseline-{scale_name}" style="{guide}" x1="263" x2="3036" y1="{base:g}" y2="{base:g}"/>')
    lines.append(f'  <line id="Capline-{scale_name}" style="{guide}" x1="263" x2="3036" y1="{cap:g}" y2="{cap:g}"/>')
svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Golda's coin in one colour, the facets cut apart. Generated by ios/tools/coin_symbol.py from tools/coin.py. -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3300" height="2200">
 <!--glyph: "{NAME}", point size: 100.0, template writer version: "coin_symbol.py"-->
 <g id="Notes">
  <rect height="2200" id="artboard" style="fill:white;opacity:1" width="3300" x="0" y="0"/>
{chr(10).join(lines)}
 </g>
 <g id="Guides">
  <line id="left-margin-Regular-M" style="{margin}" x1="{LEFT:g}" x2="{LEFT:g}" y1="1030.79" y2="1150.12"/>
  <line id="right-margin-Regular-M" style="{margin}" x1="{right:.3f}" x2="{right:.3f}" y1="1030.79" y2="1150.12"/>
 </g>
 <g id="Symbols">
  <g id="Regular-M" transform="matrix(1 0 0 1 {LEFT:g} {BASELINE:g})">
{chr(10).join(f'   <path d="{d}"/>' for d in facets)}
  </g>
 </g>
</svg>
'''

if OUT.exists():
    shutil.rmtree(OUT)
OUT.mkdir(parents=True)
(OUT / f'{NAME}.svg').write_text(svg, newline='\n')
contents = {'info': {'author': 'xcode', 'version': 1}, 'symbols': [{'filename': f'{NAME}.svg', 'idiom': 'universal'}]}
(OUT / 'Contents.json').write_text(json.dumps(contents, indent=2, separators=(',', ' : ')) + '\n', newline='\n')
catalog = OUT.parent / 'Contents.json'
if not catalog.exists():
    catalog.write_text(json.dumps({'info': {'author': 'xcode', 'version': 1}}, indent=2, separators=(',', ' : ')) + '\n', newline='\n')
print(OUT)

# A control's glyph may be looked up in the app's bundle rather than the extension's (the simulator
# shows none either way), so the app carries the same symbol.
if len(sys.argv) == 1:
    APP = ROOT / f'ios/Golda/Resources/Assets.xcassets/{NAME}.symbolset'
    if APP.exists():
        shutil.rmtree(APP)
    shutil.copytree(OUT, APP)
    print(APP)
